import pygame
def get_surface():
    surface = pygame.Surface((16, 16), pygame.SRCALPHA, 32)
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (1,1))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (2,1))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (3,1))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (4,1))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (5,1))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (1,2))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (5,2))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (6,2))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (1,3))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (6,3))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (8,3))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (9,3))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (11,3))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (1,4))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (6,4))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (8,4))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (11,4))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (1,5))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (5,5))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (6,5))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (8,5))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (9,5))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (11,5))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (1,6))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (2,6))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (3,6))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (4,6))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (5,6))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (8,6))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (11,6))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (1,7))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (8,7))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (9,7))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (10,7))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (11,7))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (12,7))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (13,7))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (14,7))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (1,8))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (1,9))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (5,9))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (8,9))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (10,9))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (14,9))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (1,10))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (5,10))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (6,10))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (7,10))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (8,10))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (10,10))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (11,10))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (13,10))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (14,10))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (1,11))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (8,11))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (11,11))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (12,11))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (13,11))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (1,12))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (5,12))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (8,12))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (10,12))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (11,12))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (13,12))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (14,12))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (0,13))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (1,13))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (2,13))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (5,13))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (6,13))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (7,13))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (8,13))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (10,13))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (14,13))
    r, g, b, a = (0, 0, 0, 255)
    square_surface = pygame.Surface((1,1), pygame.SRCALPHA)
    square_surface.fill((r,g,b)); square_surface.set_alpha(a); surface.blit(square_surface, (1,14))
    return surface